packages:
  - "apps/*"
  - "packages/*"

overrides:
  "brace-expansion@<1.1.18": "1.1.18"
  "brace-expansion@>=5.0.0 <5.0.9": "5.0.9"
  "nanoid@<3.3.18": "3.3.18"
  "postcss@<8.5.23": "8.5.26"
  "xcode>uuid": "11.1.1"

allowBuilds:
  "@swc/core": true
  core-js: true
  sharp: true
  unrs-resolver: true
  "@expo/spawn-async": true
  esbuild: true
  expo: true
  "@shopify/react-native-skia": true

minimumReleaseAgeExclude:
  - "@expo/cli@57.0.17 || 57.0.20 || 57.0.21"
  - "@expo/fingerprint@0.20.9 || 0.20.11 || 0.20.12"
  - "@expo/local-build-cache-provider@57.0.7"
  - "@expo/metro-config@57.0.9 || 57.0.12"
  - "@expo/metro-runtime@57.0.12 || 57.0.15"
  - "@expo/prebuild-config@57.0.13"
  - "@expo/router-server@57.0.7 || 57.0.9"
  - "@expo/ui@57.0.12 || 57.0.15"
  - expo-asset@57.0.13 || 57.0.16
  - expo-constants@57.0.13 || 57.0.16 || 57.0.17
  - expo-dev-client@57.0.14 || 57.0.18
  - expo-dev-launcher@57.0.14 || 57.0.19
  - expo-dev-menu@57.0.14 || 57.0.18
  - expo-file-system@57.0.5
  - expo-linking@57.0.7 || 57.0.9
  - expo-modules-core@57.0.12 || 57.0.15
  - expo-modules-jsi@57.0.5 || 57.0.7
  - expo-router@57.0.15 || 57.0.18
  - expo-sharing@57.0.14 || 57.0.17
  - expo@57.0.15 || 57.0.18 || 57.0.19
  - "@expo/env@2.4.3"
  - expo-font@57.0.2 || 57.0.3
  - babel-preset-expo@57.0.10
