name: Production Mobile Web Lighthouse Measurements

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  pages: write
  id-token: write

concurrency:
  group: mobile-web-lighthouse-production
  cancel-in-progress: true

jobs:
  lighthouse:
    uses: DoctorDerek/DoctorDerekCICD/.github/workflows/lighthouse.yml@93e29ba0fcf1d35d8ff0040002816c36d763d966
    with:
      production-url: https://www.whatareyourvaluesmapache.com/
